package Vistas.Usuario;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.EventListener;
import java.util.List;

import AppDataProgramFilms.Asiento;
import AppService.AppServiceInterfaz;
import Transfer.PeliculaTransfer;
import Transfer.SalaTransfer;
import Transfer.SesionTransfer;
import Vistas.PanelGenerico;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SkyLanes
 */
@SuppressWarnings("serial")
public class PanelReserva extends PanelGenerico {
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmacion;
    private javax.swing.JButton jButtonSelAsientos;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxFecha;
    private javax.swing.JComboBox<String> jComboBoxPeliculas;
    private javax.swing.JLabel jLabelImporte;
    private javax.swing.JLabel jLabelNumEntradas;
    private javax.swing.JLabel jLabelSelFecha;
    private javax.swing.JLabel jLabelSelPeliculas;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldNumEntradas;
    private javax.swing.JTextPane jTextPaneImporte;
    private static PanelSelAsientos panelSelAsientos;
    private List<Asiento> listaAsientos;
    // End of variables declaration//GEN-END:variables
    

    /**
     * Creates new form PanelReserva
     */
    public PanelReserva(EventListener controlador) {
        initComponents();
        fijarControlador(controlador);
        panelSelAsientos = new PanelSelAsientos(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
		this.setName("PanelReserva");
		
        jLabelTitulo = new javax.swing.JLabel();
        jButtonVolver = new javax.swing.JButton();
        jComboBoxPeliculas = new javax.swing.JComboBox<String>();
        jLabelSelPeliculas = new javax.swing.JLabel();
        jComboBoxFecha = new javax.swing.JComboBox<String>();
        jLabelSelFecha = new javax.swing.JLabel();
        jLabelNumEntradas = new javax.swing.JLabel();
        jButtonConfirmacion = new javax.swing.JButton();
        jLabelImporte = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneImporte = new javax.swing.JTextPane();
        jButtonSelAsientos = new javax.swing.JButton();
        jTextFieldNumEntradas = new javax.swing.JTextField();
        listaAsientos = new ArrayList<Asiento>();
        


        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTitulo.setText("Reservar entradas");

        jButtonVolver.setText("Volver");
        jButtonVolver.setName("jButtonVolver");
	
		jComboBoxPeliculas.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Seleccione pelicula" }));
        jComboBoxPeliculas.setName("jComboBoxBuscarPeliculaReserva");

        jLabelSelPeliculas.setText("Seleccione pelicula");

        jComboBoxFecha.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Seleccione horario" }));
        jComboBoxFecha.setName("jComboBoxSesionReserva");

        jLabelSelFecha.setText("Seleccione fecha:");

        jLabelNumEntradas.setText("Numero de entradas:");

        jButtonConfirmacion.setText("Confirmar reserva");
        jButtonConfirmacion.setName("jButtonConfirmarReserva");

        jLabelImporte.setText("Importe a pagar: ");

        jScrollPane1.setViewportView(jTextPaneImporte);

        jButtonSelAsientos.setText("Seleccione asientos");
        jButtonSelAsientos.setName("jButtonReservaAsientos");


        this.jTextPaneImporte.setText("7 Euros * entrada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jButtonVolver)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                    .addComponent(jLabelTitulo)
                    .addGap(198, 198, 198))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jButtonSelAsientos))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(170, 170, 170)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelSelFecha)
                                            .addComponent(jLabelNumEntradas)
                                            .addComponent(jLabelImporte))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(170, 170, 170)
                                    .addComponent(jLabelSelPeliculas)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(56, 56, 56)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jComboBoxPeliculas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBoxFecha, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1)
                                        .addComponent(jTextFieldNumEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    )))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(217, 217, 217)
                            .addComponent(jButtonConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(jLabelTitulo))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(jButtonVolver)))
                    .addGap(39, 39, 39)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSelPeliculas))
                    .addGap(21, 21, 21)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelSelFecha)
                        .addComponent(jComboBoxFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(21, 21, 21)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelNumEntradas)
                        .addComponent(jTextFieldNumEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelImporte, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(26, 26, 26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        
                        .addComponent(jButtonSelAsientos))
                    .addGap(32, 32, 32)
                    .addComponent(jButtonConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(28, 28, 28))
            );
        }// </editor-fold> 
    
	 /**
     * Metodo que se encarga de fijar el controlador en los elementos del panel de forma adecuada
     * @param controlador contiene el controlador encargado del panel. Tiene que escuchar ActionListener e ItemListener.
     */
	public void fijarControlador(EventListener controlador) {
		this.jComboBoxPeliculas.addActionListener((ActionListener) controlador);
		this.jComboBoxFecha.addActionListener((ActionListener) controlador);
		this.jButtonConfirmacion.addActionListener((ActionListener) controlador);
		this.jButtonSelAsientos.addActionListener((ActionListener) controlador);
		this.jButtonVolver.addActionListener((ActionListener) controlador);
	}
	
	public void addAsiento(Asiento a){
		this.listaAsientos.add(a);
	}
	
	
	/**
	 * Object[0] Pelicula seleccionada
	 * Object[1] Sesion seleccionada
	 * Object[2] Numero de entradas
	 * Object[3] Lista de butacas
	 */
	@Override
	public Object[] obtenerDatos() {
		Object[] datos = new Object[4];		
		datos[0] = this.jComboBoxPeliculas.getSelectedItem();
		datos[1] = this.jComboBoxFecha.getSelectedItem();
		datos[2] = this.jTextFieldNumEntradas.getText();
		datos[3] = this.listaAsientos;
		return datos;
	}

	public void addAsiento(int f, int c){
		this.listaAsientos.add(new Asiento(f,c));
		PanelReserva.panelSelAsientos.ocuped(f,c);
	}
	
	public static void selAsientos(){
		panelSelAsientos.arranca();
	}
	
	@Override
	public void limpiarPanel() {

        jComboBoxPeliculas.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Seleccione pelicula" }));
        jComboBoxFecha.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Seleccione horario" }));
        jTextFieldNumEntradas.setText("");	
	}

	@Override
	public void update(AppServiceInterfaz modelo, Object arg1) {
		if(arg1 != null){
			if(arg1.getClass().equals(PeliculaTransfer.class)){
				//Cargar lista de sesiones de la pelicula
				List<SesionTransfer> ls= modelo.listarSesiones(((PeliculaTransfer)arg1).getTitulo());
				if(ls != null){
					String[] s = new String[ls.size() +1];
					s[0] = "Seleccione sesion";
					for(int i = 0; i< ls.size(); ++i){
						s[i+1] = ls.get(i).getIdSala() + " " + ls.get(i).getFecha();
					}
					jComboBoxFecha.setModel(new javax.swing.DefaultComboBoxModel<String>(s));
				}
				else{
					jComboBoxFecha.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] {"No existen sesiones para esa pelicula"}));
				}
			}
			else if(arg1.getClass().equals(SalaTransfer.class)){
				PanelReserva.panelSelAsientos.setFila(((SalaTransfer)arg1).getFilas());
				PanelReserva.panelSelAsientos.setColumna(((SalaTransfer)arg1).getFilas());
				PanelReserva.panelSelAsientos.crearPanelSala();
			}
			
			else if(arg1.getClass().equals(SesionTransfer.class)){
				PanelReserva.panelSelAsientos.setButacasocupadas(((SesionTransfer)arg1).getButacasOcupadas()); // esta bien? No habria que buscar en la BD por posibles fallos temoprales
			}
			
		}
		else{
			//Cargar la lista de peliculas
			List<PeliculaTransfer> lp = modelo.listarPeliculas();
			
			if(lp != null){
				String[] ls = new String[lp.size() +1 ];
				ls[0] = "Seleccione pelicula";
				for(int i = 0; i < lp.size(); ++i){
					ls[i+1] = lp.get(i).getTitulo();
				}
				jComboBoxPeliculas.setModel(new javax.swing.DefaultComboBoxModel<String>(ls));
			}
			else{
				jComboBoxPeliculas.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "No existen peliculas" }));
			}
			
		}	
	}
}
