/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Usuario;

import java.awt.event.ActionListener;
import java.util.EventListener;
import java.util.List;

import AppService.AppServiceInterfaz;
import AppService.AppServiceSocio;
import Transfer.ReservaTransfer;
import Vistas.PanelGenerico;

/**
 *
 * @author AppDataProgramFilms
 */
@SuppressWarnings("serial")
public class PanelAnularReserva extends PanelGenerico {
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxReservas;
    private javax.swing.JLabel jLabelSelReserva;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables
    

    /**
     * Creates new form PanelBajaSesion
     */
    public PanelAnularReserva(EventListener controlador) {
        initComponents();
        this.fijarControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	this.setName("PanelAnularReserva");

        jButtonVolver = new javax.swing.JButton();
        jButtonConfirmar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelSelReserva = new javax.swing.JLabel();
        jComboBoxReservas = new javax.swing.JComboBox<String>();

        jButtonVolver.setText("Volver");
        jButtonVolver.setName("jButtonVolver");

        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.setName("jButtonConfirmarBajaReserva");

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTitulo.setText("Anular reserva");

        jLabelSelReserva.setText("Seleccione reserva:");

        jComboBoxReservas.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Seleccione reserva" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButtonVolver)
                        .addGap(99, 99, 99)
                        .addComponent(jLabelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabelSelReserva)
                        .addGap(60, 60, 60)
                        .addComponent(jComboBoxReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 265, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButtonVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabelTitulo)))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSelReserva)
                    .addComponent(jComboBoxReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
	 /**
     * Metodo que se encarga de fijar el controlador en los elementos del panel de forma adecuada
     * @param controlador contiene el controlador encargado del panel. Tiene que escuchar ActionListener e ItemListener.
     */
	public void fijarControlador(EventListener controlador) {		
		this.jButtonConfirmar.addActionListener((ActionListener) controlador);
		this.jButtonVolver.addActionListener((ActionListener) controlador);
	}

	/**
	 * Object[0] el id de la reserva a dar de baja
	 */
	@Override
	public Object[] obtenerDatos() {
		String id = this.jComboBoxReservas.getSelectedItem().toString();
		String[] aux = id.split(" ");
		
		Object[] datos = {aux[0]};
		return datos;
	}

	@Override
	public void limpiarPanel() {
        jComboBoxReservas.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Seleccione reserva" }));	
	}

	@Override
	public void update(AppServiceInterfaz modelo, Object arg1) {
		List<ReservaTransfer> lr = ((AppServiceSocio)modelo).listarReservas(AppServiceSocio.getSocio().getNIF());
				
		if(lr != null && lr.size()>0){
			String[] ls = new String[lr.size() +1 ];
			
			ls[0] = "Seleccione reserva";
			for(int i = 0; i < lr.size(); ++i){
				if(lr.get(i).getListaButacas() != null && lr.get(i).getListaButacas().size()>0 )
				ls[i+1] = lr.get(i).getId().toString() + " - " + lr.get(i).getListaButacas().get(0).getSesion().getTituloPelicula();
			}
			this.jComboBoxReservas.setModel(new javax.swing.DefaultComboBoxModel<String>(ls));
			}
		else{
			jComboBoxReservas.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Usted no ha realzado ninguna reserva" }));
			
		}
		
	}
}
