/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Administrador;

import java.awt.event.ActionListener;
import java.util.EventListener;
import java.util.List;

import AppService.AppServiceInterfaz;
import Transfer.PeliculaTransfer;
import Transfer.SesionTransfer;
import Vistas.PanelGenerico;

/**
 *
 * @author AppDataProgramFilms
 */
@SuppressWarnings("serial")
public class PanelBajaSesion extends PanelGenerico {
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxPeliSesiones;
    private javax.swing.JComboBox<String> jComboBoxSesion;
    private javax.swing.JLabel jLabelSelSesion;
    private javax.swing.JLabel jLabelSesion;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables
    

    /**
     * Creates new form PanelBajaSesion
     */
    public PanelBajaSesion(EventListener controlador) {
        initComponents();
        this.fijarControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	this.setName("PanelBajaSesion");

        jButtonVolver = new javax.swing.JButton();
        jButtonConfirmar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelSelSesion = new javax.swing.JLabel();
        jComboBoxPeliSesiones = new javax.swing.JComboBox<String>();
        jLabelSesion = new javax.swing.JLabel();
        jComboBoxSesion = new javax.swing.JComboBox<String>();

        jButtonVolver.setText("Volver");
        jButtonVolver.setName("jButtonVolver");

        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.setName("jButtonConfirmarBajaSesion");

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTitulo.setText("Dar de baja sesion");

        jLabelSelSesion.setText("Seleccione pelicula:");
        jLabelSelSesion.setToolTipText("");

        jComboBoxPeliSesiones.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Seleccion pelicula" }));
        jComboBoxPeliSesiones.setName("jComboBoxBajaPeliSesiones");
    
        jLabelSesion.setText("Seleccione sesion:");

        jComboBoxSesion.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Seleccione sesion" }));
        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabelTitulo)))
                .addGap(0, 226, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButtonVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelSelSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxPeliSesiones, 0, 146, Short.MAX_VALUE)
                            .addComponent(jComboBoxSesion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButtonVolver)
                .addGap(7, 7, 7)
                .addComponent(jLabelTitulo)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSelSesion)
                    .addComponent(jComboBoxPeliSesiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSesion)
                    .addComponent(jComboBoxSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }
    
    
	 /**
     * Metodo que se encarga de fijar el controlador en los elementos del panel de forma adecuada
     * @param controlador contiene el controlador encargado del panel. Tiene que escuchar ActionListener e ItemListener.
     */
	public void fijarControlador(EventListener controlador) {
		
		this.jButtonConfirmar.addActionListener((ActionListener) controlador);
		this.jButtonVolver.addActionListener((ActionListener) controlador);
		this.jComboBoxPeliSesiones.addActionListener((ActionListener) controlador);
	}
	
	/**
	 * Object[0] el titulo de la pelicula
	 * Object[1] la sala y horario
	 */
	@Override
	public Object[] obtenerDatos() {
		Object[] datos = new Object[2];
		
		datos[0] = this.jComboBoxPeliSesiones.getSelectedItem();
		datos[1] = this.jComboBoxSesion.getSelectedItem();

		return datos;
	}

	@Override
	public void limpiarPanel() {
		jComboBoxPeliSesiones.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Seleccion pelicula" }));
        jComboBoxSesion.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Seleccione sesion" }));
	}

	@Override
	public void update(AppServiceInterfaz modelo, Object arg1) {
		if(arg1 != null){
			//Cargar lista de sesiones de la pelicula
			List<SesionTransfer> ls= modelo.listarSesiones(((PeliculaTransfer)arg1).getTitulo());
			if(ls != null){
				String[] s = new String[ls.size() +1];
				s[0] = "Seleccione sesion";
				for(int i = 0; i< ls.size(); ++i){
					s[i+1] = ls.get(i).toStringReducido();
				}
				jComboBoxSesion.setModel(new javax.swing.DefaultComboBoxModel<String>(s));
			}
			else{
				jComboBoxSesion.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] {"No existen sesiones para esa pelicula"}));
			}
		}
		else{
			//Cargar la lista de peliculas
			List<PeliculaTransfer> lp = modelo.listarPeliculas();
			
			if(lp != null){
				String[] ls = new String[lp.size() +1 ];
				ls[0] = "Seleccione pelicula";
				for(int i = 0; i < lp.size(); ++i){
					ls[i+1] = lp.get(i).getTitulo();
				}
				jComboBoxPeliSesiones.setModel(new javax.swing.DefaultComboBoxModel<String>(ls));
			}
			else{
				jComboBoxPeliSesiones.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "No existen peliculas" }));
			}
			
		}
	}

	
}
