/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Administrador;

import java.awt.event.ActionListener;
import java.util.EventListener;
import java.util.List;

import AppService.AppServiceInterfaz;
import Transfer.SalaTransfer;
import Vistas.PanelGenerico;

/**
 *
 * @author AppDataProgramFilms
 */
@SuppressWarnings("serial")
public class PanelBajaSala extends PanelGenerico {
	
	
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxSalas;
    private javax.swing.JLabel jLabelSelSala;
    private javax.swing.JLabel jLabelTitulo;

    /**
     * Creates new form PanelBajaSala
     */
    public PanelBajaSala(EventListener controlador) {
        initComponents();
        this.fijarControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	this.setName("PanelBajaSala");

        jButtonVolver = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelSelSala = new javax.swing.JLabel();
        jComboBoxSalas = new javax.swing.JComboBox<String>();
        jButtonConfirmar = new javax.swing.JButton();

        jButtonVolver.setText("Volver");
        jButtonVolver.setName("jButtonVolver");

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTitulo.setText("Dar de baja una sala");

        jLabelSelSala.setText("Seleccione sala:");

        jComboBoxSalas.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Seleccione sala" }));
        
        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.setName("jButtonConfirmarBajaSala");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButtonVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addGap(200, 200, 200))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabelSelSala)
                        .addGap(66, 66, 66)
                        .addComponent(jComboBoxSalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButtonVolver)))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSelSala)
                    .addComponent(jComboBoxSalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
	 /**
     * Metodo que se encarga de fijar el controlador en los elementos del panel de forma adecuada
     * @param controlador contiene el controlador encargado del panel. Tiene que escuchar ActionListener e ItemListener.
     */
	public void fijarControlador(EventListener controlador) {
		
		this.jButtonConfirmar.addActionListener((ActionListener) controlador);
		this.jButtonVolver.addActionListener((ActionListener) controlador);
	}

	@Override
	public Object[] obtenerDatos() {
		Object[] datos = new Object[1];
		
		datos[0] =  this.jComboBoxSalas.getSelectedItem();

		return datos;
	}

	@Override
	public void limpiarPanel() {
		jComboBoxSalas.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Seleccione sala" }));		
	}

	@Override
	public void update(AppServiceInterfaz modelo, Object arg1) {
		List<SalaTransfer> lp = modelo.listarSalas();
		
		if(lp != null){
			String[] ls = new String[lp.size() +1 ];
			ls[0] = "Seleccione sala";
			for(int i = 0; i < lp.size(); ++i){
				ls[i+1] = lp.get(i).getId().toString();
			}
			jComboBoxSalas.setModel(new javax.swing.DefaultComboBoxModel<String>(ls));
		}
		else{
			jComboBoxSalas.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "No existen salas" }));		
			
		}
	}

}
