/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Administrador;

import java.awt.event.ActionListener;
import java.util.EventListener;
import java.util.List;

import AppService.AppServiceInterfaz;
import Enumerados.Genero;
import Transfer.PeliculaTransfer;
import Vistas.PanelGenerico;

/**
 *
 * @author MIGUEL
 */
@SuppressWarnings("serial")
public class PanelEditarPelicula extends PanelGenerico {
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxGenero;
    private javax.swing.JComboBox<String> jComboBoxPeliculas;
    private javax.swing.JLabel jLabelActores;
    private javax.swing.JLabel jLabelDirector;
    private javax.swing.JLabel jLabelDuracion;
    private javax.swing.JLabel jLabelEditarPelicula;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelSelPelicula;
    private javax.swing.JLabel jLabelSinopsis;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldActores;
    private javax.swing.JTextField jTextFieldDirector;
    private javax.swing.JTextField jTextFieldDuracion;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldTitulo;
    private javax.swing.JTextPane jTextPaneSinopsis;
    // End of variables declaration//GEN-END:variables
    

    /**
     * Creates new form PanelEditarPelicula
     */
    public PanelEditarPelicula(EventListener controlador) {
        initComponents();
        this.fijarControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
		this.setName("PanelEditarPelicula");
        
		 jButtonVolver = new javax.swing.JButton();
	     jLabelEditarPelicula = new javax.swing.JLabel();
	     jButtonConfirmar = new javax.swing.JButton();
	     jLabelTitulo = new javax.swing.JLabel();
	     jLabelGenero = new javax.swing.JLabel();
	     jLabelDuracion = new javax.swing.JLabel();
	     jComboBoxGenero = new javax.swing.JComboBox<String>();
	     jLabelFecha = new javax.swing.JLabel();
	     jLabelSinopsis = new javax.swing.JLabel();
	     jLabelSelPelicula = new javax.swing.JLabel();
	     jComboBoxPeliculas = new javax.swing.JComboBox<String>();
	     jLabelActores = new javax.swing.JLabel();
	     jLabelDirector = new javax.swing.JLabel();
	     jTextFieldTitulo = new javax.swing.JTextField();
	     jTextFieldDuracion = new javax.swing.JTextField();
	     jTextFieldFecha = new javax.swing.JTextField();
	     jTextFieldDirector = new javax.swing.JTextField();
	     jTextFieldActores = new javax.swing.JTextField();
	     jScrollPane1 = new javax.swing.JScrollPane();
	     jTextPaneSinopsis = new javax.swing.JTextPane();

        setPreferredSize(new java.awt.Dimension(600, 400));

        jButtonVolver.setText("Volver");
        jButtonVolver.setName("jButtonVolver");

        jLabelEditarPelicula.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelEditarPelicula.setText("Editar una pelicula");

        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.setName("jButtonConfirmarEditarPelicula");

        jLabelTitulo.setText("Titulo:");

        jLabelGenero.setText("Genero:");

        jLabelDuracion.setText("Duracion:");

        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<String>(Genero.valuesString()));

        jLabelFecha.setText("Fecha de estreno:");

        jLabelSinopsis.setText("Sinopsis:");

        jLabelSelPelicula.setText("Seleccione la pelicula:");

        jComboBoxPeliculas.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Seleccione pelicula" }));
        jComboBoxPeliculas.setName("jComboBoxEditarPeliculas");
        
        jLabelActores.setText("Actores:");

        jLabelDirector.setText("Director:");
        
        jScrollPane1.setViewportView(jTextPaneSinopsis);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelActores, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTitulo)
                    .addComponent(jLabelSelPelicula)
                    .addComponent(jLabelGenero)
                    .addComponent(jLabelDuracion)
                    .addComponent(jLabelFecha)
                    .addComponent(jLabelSinopsis)
                    .addComponent(jLabelDirector))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldDuracion, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldDirector, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldActores, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButtonVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(jLabelEditarPelicula)
                .addGap(190, 190, 190))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEditarPelicula)
                    .addComponent(jButtonVolver))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSelPelicula)
                    .addComponent(jComboBoxPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGenero)
                            .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDuracion)
                            .addComponent(jTextFieldDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFecha)
                    .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDirector)
                    .addComponent(jTextFieldDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelActores)
                    .addComponent(jTextFieldActores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabelSinopsis)
                        .addContainerGap(61, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
	 /**
     * Metodo que se encarga de fijar el controlador en los elementos del panel de forma adecuada
     * @param controlador contiene el controlador encargado del panel. Tiene que escuchar ActionListener e ItemListener.
     */
	public void fijarControlador(EventListener controlador) {
		this.jButtonConfirmar.addActionListener((ActionListener) controlador);
		this.jButtonVolver.addActionListener((ActionListener) controlador);
		this.jComboBoxPeliculas.addActionListener((ActionListener) controlador);
	}

	/**
	 * Object[0] el titulo de la pelicula a modificar
	 * Object[1] el titulo de la pelicula(STRING)
	 * Object[2] el genero (String)
	 * Object[3] la synopsis(String)
	 * Object[4] la fechaHora (String)
	 * Object[5] los actores (String)
	 * Object[6] el director (String)
	 * Object[7] la duracion (int)
	 */
	@Override
	public Object[] obtenerDatos() {
		Object[] datos = new Object[8];
		
		datos[0] = this.jComboBoxPeliculas.getSelectedItem();
		datos[1] = this.jTextFieldTitulo.getText();
		datos[2] = this.jComboBoxGenero.getSelectedItem();
		datos[3] = this.jTextPaneSinopsis.getText();
		datos[4] = this.jTextFieldFecha.getText();
		datos[5] = this.jTextFieldActores.getText();
		datos[6] = this.jTextFieldDirector.getText();
		datos[7] = this.jTextFieldDuracion.getText();

		return datos;
	}

	@Override
	public void limpiarPanel() {
		jComboBoxPeliculas.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Seleccione pelicula" }));
		this.jTextFieldTitulo.setText("");
		this.jTextPaneSinopsis.setText("");
		this.jTextFieldFecha.setText("");
		this.jTextFieldActores.setText("");
		this.jTextFieldDirector.setText("");
		this.jTextFieldDuracion.setText("");
	}

	@Override
	public void update(AppServiceInterfaz modelo, Object arg1) {
		if(arg1 != null){
			PeliculaTransfer p  = (PeliculaTransfer)arg1;
			
			this.jComboBoxGenero.setSelectedItem((Object)p.getGenero().toString());
			this.jComboBoxPeliculas.setSelectedItem((Object)p.getTitulo()); 			
			this.jTextFieldTitulo.setText(p.getTitulo());
			this.jTextPaneSinopsis.setText(p.getSynopsis());
			this.jTextFieldFecha.setText(p.getFechaEstreno());
			this.jTextFieldActores.setText(p.getActores());
			this.jTextFieldDirector.setText(p.getDirector());
			this.jTextFieldDuracion.setText(Integer.valueOf(p.getDuracion()).toString());
		}
		else{
			List<PeliculaTransfer> lp = modelo.listarPeliculas();
			String[] ls = new String[lp.size() +1 ];
			
			ls[0] = "Seleccione pelicula";
			for(int i = 0; i < lp.size(); ++i){
				ls[i+1] = lp.get(i).getTitulo();
			}
			this.jComboBoxPeliculas.setModel(new javax.swing.DefaultComboBoxModel<String>(ls));
		}
	}
}
