package Vistas.Administrador;

import java.awt.event.ActionListener;
import java.util.EventListener;
import java.util.List;

import AppService.AppServiceAdmin;
import AppService.AppServiceInterfaz;
import Transfer.SocioTransfer;
import Vistas.PanelGenerico;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SkyLanes
 */
@SuppressWarnings("serial")
public class PanelBuscarSocio extends PanelGenerico{
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxSocios;
    private javax.swing.JLabel jLabelSelecSocio;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPaneInfoSocio;
    // End of variables declaration//GEN-END:variables
    

    /**
     * Creates new form PanelPeliculas
     */
    public PanelBuscarSocio(EventListener controlador) {
        initComponents();
        this.fijarControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	this.setName("PanelBuscarSocio");

    	 jLabelSelecSocio = new javax.swing.JLabel();
         jButtonVolver = new javax.swing.JButton();
         jLabelTitulo = new javax.swing.JLabel();
         jScrollPane1 = new javax.swing.JScrollPane();
         jTextPaneInfoSocio = new javax.swing.JTextPane();
         jComboBoxSocios = new javax.swing.JComboBox<String>();
        
        setPreferredSize(new java.awt.Dimension(600, 400));

        jLabelSelecSocio.setText("Introduzca usuario:");
        
        jComboBoxSocios.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Seleccione socio" }));	
        jComboBoxSocios.setName("jComboBoxBuscarSocio");

        jButtonVolver.setText("Volver");
        jButtonVolver.setName("jButtonVolver");

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTitulo.setText("Buscar socio");

        jScrollPane1.setViewportView(jTextPaneInfoSocio);


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButtonVolver)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSelecSocio)
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxSocios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxSocios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButtonVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelSelecSocio)
                        .addGap(32, 32, 32)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents
    
	 /**
     * Metodo que se encarga de fijar el controlador en los elementos del panel de forma adecuada
     * @param controlador contiene el controlador encargado del panel. Tiene que escuchar ActionListener e ItemListener.
     */
	public void fijarControlador(EventListener controlador) {
		this.jButtonVolver.addActionListener((ActionListener) controlador);
		this.jComboBoxSocios.addActionListener((ActionListener) controlador);
	}

	/**
	 * Devuelve en el array datos[0] el texto contenido en el textField, que sera el usuario que se desea buscar
	 */
	@Override
	public Object[] obtenerDatos() {
		Object[] datos = new Object[1];
		
		datos[0] = this.jComboBoxSocios.getSelectedItem();

		return datos;
	}

	@Override
	public void limpiarPanel() {
		  jComboBoxSocios.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Seleccione socio" }));	
	}

	@Override
	public void update(AppServiceInterfaz modelo, Object arg1) {
		if(arg1 != null){
			this.jTextPaneInfoSocio.setText(((SocioTransfer)arg1).toString())	;	
		}
		else{
			List<SocioTransfer> lp = ((AppServiceAdmin)modelo).listarSocios();
			String[] ls = new String[lp.size() +1 ];
			
			ls[0] = "Seleccione pelicula";
			for(int i = 0; i < lp.size(); ++i){
				ls[i+1] = lp.get(i).getNIF();
			}
			this.jComboBoxSocios.setModel(new javax.swing.DefaultComboBoxModel<String>(ls));
		}
	}
}
