/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Administrador;

import java.awt.event.ActionListener;
import java.util.EventListener;

import AppService.AppServiceInterfaz;
import Vistas.PanelGenerico;

/**
 *
 * @author MIGUEL
 */
@SuppressWarnings("serial")
public class PanelAltaSala extends PanelGenerico {
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelAltaSala;
    private javax.swing.JLabel jLabelFilas;
    private javax.swing.JLabel jLabelNumButacas;
    private javax.swing.JLabel jLabelNumSala;
    private javax.swing.JTextField jTextFieldNumButacas;
    private javax.swing.JTextField jTextFieldNumFilas;
    private javax.swing.JTextField jTextFieldNumSala;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form PanelAltaSala
     */
    public PanelAltaSala(EventListener controlador) {
        initComponents();
        this.fijarControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	this.setName("PanelAltaSala");

        jLabelAltaSala = new javax.swing.JLabel();
        jButtonVolver = new javax.swing.JButton();
        jLabelFilas = new javax.swing.JLabel();
        jLabelNumButacas = new javax.swing.JLabel();
        jLabelNumSala = new javax.swing.JLabel();
        jButtonConfirmar = new javax.swing.JButton();
        jTextFieldNumSala = new javax.swing.JTextField();
        jTextFieldNumFilas = new javax.swing.JTextField();
        jTextFieldNumButacas = new javax.swing.JTextField();

        jLabelAltaSala.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelAltaSala.setText("Alta de sala");

        jButtonVolver.setText("Volver");
        jButtonVolver.setName("jButtonVolver");

        jLabelFilas.setText("Numero de filas:");

        jLabelNumButacas.setText("Numero de butacas:");

        jLabelNumSala.setText("Numero de sala:");

        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.setName("jButtonConfirmarAltaSala");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelNumSala, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelFilas, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabelNumButacas))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNumSala, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(jTextFieldNumFilas)
                            .addComponent(jTextFieldNumButacas)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButtonVolver)
                        .addGap(132, 132, 132)
                        .addComponent(jLabelAltaSala)))
                .addGap(0, 219, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVolver)
                    .addComponent(jLabelAltaSala, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumSala, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFilas)
                    .addComponent(jTextFieldNumFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumButacas)
                    .addComponent(jTextFieldNumButacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
	 /**
     * Metodo que se encarga de fijar el controlador en los elementos del panel de forma adecuada
     * @param controlador contiene el controlador encargado del panel. Tiene que escuchar ActionListener e ItemListener.
     */
	public void fijarControlador(EventListener controlador) {
		this.jButtonConfirmar.addActionListener((ActionListener) controlador);
		this.jButtonVolver.addActionListener((ActionListener) controlador);
	}
	
	
	
	/**
	 * Object[0] el id de la sala
	 * Object[1] el numero de filas
	 * Object[2] el numero de butacas por fila
	 */
	@Override
	public Object[] obtenerDatos() {
		Object[] datos = new Object[3];
		
		datos[0] = this.jTextFieldNumSala.getText();
		datos[1] = this.jTextFieldNumFilas.getText();
		datos[2] = this.jTextFieldNumButacas.getText();
	
		return datos;
	}

	@Override
	public void limpiarPanel() {
		this.jTextFieldNumButacas.setText("");
		this.jTextFieldNumFilas.setText("");
		this.jTextFieldNumSala.setText("");		
	}

	/**
	 * No se necesita
	 */
	@Override
	public void update(AppServiceInterfaz modelo, Object arg1) {}
    
}
