/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Administrador;

import java.awt.event.ActionListener;
import java.util.EventListener;

import AppService.AppServiceInterfaz;
import Vistas.PanelGenerico;

/**
 *
 * @author SkyLanes
 */
@SuppressWarnings("serial")
public class PanelPrincipalAdmin extends PanelGenerico {
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditarAdmin;
    private javax.swing.JButton jButtonPelicula;
    private javax.swing.JButton jButtonSala;
    private javax.swing.JButton jButtonSesion;
    private javax.swing.JButton jButtonSocio;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables
    

    /**
     * Creates new form PanelDarDeAlta
     */
    public PanelPrincipalAdmin(EventListener controlador) {
        initComponents();
        this.fijarControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	this.setName("PanelPrincipalAdmin");
    	
        jButtonVolver = new javax.swing.JButton();
        jButtonPelicula = new javax.swing.JButton();
        jButtonSala = new javax.swing.JButton();
        jButtonSesion = new javax.swing.JButton();
        jButtonSocio = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonEditarAdmin = new javax.swing.JButton();

        jButtonVolver.setText("Logout");
        jButtonVolver.setName("jButtonLogout");

        jButtonPelicula.setText("Pelicula");
        jButtonPelicula.setName("jButtonSeleccionAdminPelicula");

        jButtonSala.setText("Sala");
        jButtonSala.setName("jButtonSeleccionAdminSala");

        jButtonSesion.setText("Sesion");
        jButtonSesion.setName("jButtonSeleccionAdminSesion");


        jButtonSocio.setText("Socio");
        jButtonSocio.setName("jButtonSeleccionAdminSocio");

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTitulo.setText("Administrador");

        jButtonEditarAdmin.setText("Editar cuenta");
        jButtonEditarAdmin.setName("jButtonSeleccionAdminEditarAdmin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButtonVolver)
                        .addGap(132, 132, 132)
                        .addComponent(jLabelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSala, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jButtonEditarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButtonVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabelTitulo)))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSala, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jButtonEditarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
	 /**
     * Metodo que se encarga de fijar el controlador en los elementos del panel de forma adecuada
     * @param controlador contiene el controlador encargado del panel. Tiene que escuchar ActionListener e ItemListener.
     */
	public void fijarControlador(EventListener controlador) {
		
		this.jButtonVolver.addActionListener((ActionListener) controlador);
		this.jButtonPelicula.addActionListener((ActionListener) controlador);
		this.jButtonSala.addActionListener((ActionListener) controlador);
		this.jButtonSesion.addActionListener((ActionListener) controlador);
		this.jButtonSocio.addActionListener((ActionListener) controlador);
		this.jButtonEditarAdmin.addActionListener((ActionListener) controlador);
	}

	@Override
	public Object[] obtenerDatos() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void limpiarPanel() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void update(AppServiceInterfaz modelo, Object arg1) {
		// TODO Auto-generated method stub
		
	}

    
}
