/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Administrador;

import java.awt.event.ActionListener;
import java.util.EventListener;
import java.util.List;

import AppService.AppServiceInterfaz;
import Transfer.PeliculaTransfer;
import Transfer.SalaTransfer;
import Vistas.PanelGenerico;


/**
 *
 * @author AppDataProgramFilms
 */
@SuppressWarnings("serial")
public class PanelAltaSesion extends PanelGenerico {
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JComboBox<String> jComboBoxPelicula;
    private javax.swing.JComboBox<String> jComboBoxSala;
    private javax.swing.JLabel jLabelAltaSesion;
    private javax.swing.JLabel jLabelSelHorario;
    private javax.swing.JLabel jLabelSelPelicula;
    private javax.swing.JLabel jLabelSelSala;
    private javax.swing.JTextField jTextFieldHorario;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form PanelAltaSesion
     */
    public PanelAltaSesion(EventListener controlador) {
        initComponents();
        this.fijarControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	this.setName("PanelAltaSesion");

        jButtonVolver = new javax.swing.JButton();
        jLabelAltaSesion = new javax.swing.JLabel();
        jLabelSelPelicula = new javax.swing.JLabel();
        jComboBoxPelicula = new javax.swing.JComboBox<String>();
        jLabelSelSala = new javax.swing.JLabel();
        jComboBoxSala = new javax.swing.JComboBox<String>();
        jLabelSelHorario = new javax.swing.JLabel();
        jButtonConfirmar = new javax.swing.JButton();
        jTextFieldHorario = new javax.swing.JTextField();

        jButtonVolver.setText("Volver");
        jButtonVolver.setName("jButtonVolver");

        jLabelAltaSesion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelAltaSesion.setText("Alta de sesion");

        jLabelSelPelicula.setText("Seleccione pelicula:");

        jComboBoxPelicula.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Seleccione pelicula" }));
       

        jLabelSelSala.setText("Seleccione sala:");

        jComboBoxSala.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Seleccione sala" }));
		

        jLabelSelHorario.setText("Seleccione horario:");

        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.setName("jButtonConfirmarAltaSesion");

        jTextFieldHorario.setText("YYYY-MM-DD HH:MM:SS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButtonVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSelSala)
                            .addComponent(jLabelSelPelicula)
                            .addComponent(jLabelSelHorario))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxPelicula, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxSala, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldHorario, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAltaSesion)
                    .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 238, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButtonVolver)
                .addGap(7, 7, 7)
                .addComponent(jLabelAltaSesion)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSelPelicula)
                    .addComponent(jComboBoxPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSelSala)
                    .addComponent(jComboBoxSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSelHorario)
                    .addComponent(jTextFieldHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    
	 /**
     * Metodo que se encarga de fijar el controlador en los elementos del panel de forma adecuada
     * @param controlador contiene el controlador encargado del panel. Tiene que escuchar ActionListener e ItemListener.
     */
	public void fijarControlador(EventListener controlador) {
		this.jButtonConfirmar.addActionListener((ActionListener) controlador);
		this.jButtonVolver.addActionListener((ActionListener) controlador);
	}
	

		/**
	 * Object[0] titulo de la pelicula (STRING)
	 * Object[1] id de la sala (STRING)
	 * Object[2] Hora (hh:mm:00)
	 */
	@Override
	public Object[] obtenerDatos() {
		Object[] datos = new Object[3];
		
		datos[0] = this.jComboBoxPelicula.getSelectedItem();
		datos[1] = this.jComboBoxSala.getSelectedItem();
		datos[2] = this.jTextFieldHorario.getText();
		
		return datos;
	}

	@Override
	public void limpiarPanel() {
		jComboBoxPelicula.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Seleccione sesion" }));
        jComboBoxSala.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Seleccione sala" }));
        jTextFieldHorario.setText("YYYY-MM-DD HH:MM:SS");
	}

	/**
	 * No es necesario
	 */
	@Override
	public void update(AppServiceInterfaz modelo, Object arg1) {
		//Anyadimos las peliculas
		List<PeliculaTransfer> lp = modelo.listarPeliculas();
		if(lp != null){
			String[] l = new String[lp.size() +1 ];
			
			l[0] = "Seleccione pelicula";
			for(int i = 0; i < lp.size(); ++i){
				l[i+1] = lp.get(i).getTitulo();
			}
			this.jComboBoxPelicula.setModel(new javax.swing.DefaultComboBoxModel<String>(l));
		}
		else{
			this.jComboBoxPelicula.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "No existen peliculas"}));
		}
		
		//Anyadimos las salas
		List<SalaTransfer> ls = modelo.listarSalas();
		
		if(ls != null){
			String[] l = new String[ls.size() +1 ];
			l[0] = "Seleccione sala";
			for(int i = 0; i < ls.size(); ++i){
				l[i+1] = ls.get(i).getId().toString();
			}
			jComboBoxSala.setModel(new javax.swing.DefaultComboBoxModel<String>(l));
		}
		else{
			jComboBoxSala.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "No existen salas" }));		
			
		}
		
	}
}
